## USB port
port: /dev/ttyUSB0


##### Calibration ####
### accelerometer
accel_x_min: -265.0
accel_x_max: 245.0
accel_y_min: -248.0
accel_y_max: 267.0
accel_z_min: -276.0
accel_z_max: 230.0

### magnetometer
# standard calibration
magn_x_min: -633.0
magn_x_max: 516.0
magn_y_min: -520.0
magn_y_max: 462.0
magn_z_min: -434.0
magn_z_max: 458.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [-54.4809, -28.9563, 12.9810]
magn_ellipsoid_transform: [[0.767972, 0.00176574, -0.00920111], [0.00176574, 0.884199, 0.0245766], [-0.00920111, 0.0245766, 0.994448]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -31.64
gyro_average_offset_y: -4.51
gyro_average_offset_z: 4.87
